### ISSUE TITLE
All styles removed if template is updated

### ISSUE THREAD

**Issue by rob-balfre** [sveltejs/svelte-hackernews#6]
Noticed that any changes to a component's template removes all styles.  Only solution is to delete the generated component from the server folder.

Maybe I just don't know what I'm doing?!!

To reproduce:

```bash
yarn
npm run build:both
npm run dev
```

Visit http://localhost:3000/

Make a small change to /shared/components/Nav.html

```html
...
<li><a class='{{route === "top"  ? "selected" : ""}}' href='/top/1'>test</a></li>
...
```

Refresh http://localhost:3000/

**Comment by Rich-Harris** [comment]
Yes, this is totally infuriating 😀

This was the first time I built a Svelte app with server-rendered HTML and CSS, and I hadn't yet figured out a good workflow. Basically what's happening here is that the CSS is rendered once in [a rather kludgy way here](https://github.com/sveltejs/svelte-hackernews/blob/36e225d03dcd3d5823e86d85e50545de37660f68/build.js#L20-L39), and because the CSS scoping mechanism uses a checksum of the template, editing the template causes a mismatch. The CSS is still there, but it no longer applies to the component in question.

It's now possible to extract the CSS directly from the bundle each time it's generated using rollup-plugin-svelte: https://github.com/rollup/rollup-plugin-svelte#extracting-css. That way you get server-rendered CSS, but it's always current.

I'll update this repo to use the same technique.

**Comment by rob-balfre** [comment]
@Rich-Harris Thanks for explaining and updating the repo. You're on 🔥 with all this Rollup and Svelte goodness!
